exp_name: cityscapes_2task
seed: [88, 45, 50, 100, 44, 48, 2048, 2222, 23, 12, 94, 88, 1000, 42, 77, 666]
backbone: ResNet34
tasks: ["seg", "depth"]
lambdas: [1, 20]
tasks_num_class: [19, 1]
policy_model: task-specific


paths:
  log_dir: experiments/logs/
  result_dir: experiments/results
  checkpoint_dir: experiments/checkpoints

dataload:
  dataset: CityScapes
  dataroot: "../datasets/cityscapes"
  small_res: False
  crop_h: 224
  crop_w: 224

policy: True
init_neg_logits:
is_sparse: True
is_sharing: True
skip_layer: 0
is_curriculum: True
curriculum_speed: 3
fix_BN: False
diff_sparsity_weights: True
retrain_from_pl: False


train:
  batch_size: 16
  total_iters: 20000
  warm_up_iters: 4000
  lr: 0.0001
  policy_lr: 0.01
  backbone_lr: 0.001
  reg_w: 0.01
  reg_w_hamming: 0.1
  print_freq: 100
  val_freq: 400
  decay_lr_freq: 4000
  decay_lr_rate: 0.5
  decay_temp_freq: 100
  init_temp: 5
  decay_temp: 0.965
  resume: False
  retrain_resume: False
  policy_iter: best
  which_iter: warmup
  init_method: equal
  hard_sampling: False

test:
  which_iter: best
